"""Prepare a per-scale training workspace.

For a chosen scale (10k/50k/100k/185k) and CoT model (e.g. Qwen2.4_VL_72B_Instruct_AWQ):

  1. Stream-extract the sample-JSON tarballs from /backup/nuplan_nuscenes_train_mix/
     into /data/nuplan_nuscenes_train_mix_<scale>/{nuPlan,nuScenes}/. Which
     tarballs are extracted depends on --datasets (nuplan / nuscenes / both).
  2. Walk those JSONs to build the set of raw image paths actually referenced.
  3. When nuplan is selected: stream-extract raw nuPlan from
     /backup/raw_dataset_tarball/nuplan/ into /data/nuPlan/{navsim_logs,sensor_blobs}/trainval/.
  4. When nuscenes is selected: stream-extract raw nuScenes (samples/CAM_<6> +
     v1.0-trainval/), AND copy /backup/drivelm/ → /data/drivelm/ (the nuScenes
     DriveLM Q&A JSONs travel with the nuScenes hydration).

Camera pruning is configurable via --num-cameras:
  - 3 (default): the cameras SFTDataset / RL inference actually read at training
    time — nuPlan = F0 + L1 + R1, nuScenes = front + front_left + front_right.
  - 4: adds the back camera, matching the CoT-annotation prompt set used by
    NuplanCoTAnnotationDataset and NuscenesCoTAnnotationDataset.
Sweeps + LIDAR/RADAR samples are excluded for nuScenes regardless.

Resumable: re-running with the same args is safe; existing files are skipped, so
running --scale 10k after --scale 50k does almost no work for raw data.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tarfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from time import perf_counter


BACKUP_SCALING_DIR = Path("/backup/nuplan_nuscenes_train_mix")
BACKUP_RAW_NUPLAN  = Path("/backup/raw_dataset_tarball/nuplan")
BACKUP_RAW_NUSC    = Path("/backup/raw_dataset_tarball/nuscenes")
BACKUP_DRIVELM     = Path("/backup/drivelm")
DATA_ROOT          = Path("/data")
NUPLAN_RAW         = DATA_ROOT / "nuPlan"
NUSC_RAW           = DATA_ROOT / "nuScenes"
DRIVELM_DST        = DATA_ROOT / "drivelm"

SCALES = ("10k", "50k", "100k", "185k")
DATASETS = ("nuplan", "nuscenes", "both")


def sync_drivelm():
    """Copy /backup/drivelm/*.json → /data/drivelm/ (skips files already present
    with matching size). nuScenes-only artifact; called from any flow that
    hydrates nuScenes."""
    DRIVELM_DST.mkdir(parents=True, exist_ok=True)
    copied = skipped = 0
    for src in sorted(BACKUP_DRIVELM.glob("*.json")):
        dst = DRIVELM_DST / src.name
        if dst.exists() and dst.stat().st_size == src.stat().st_size:
            skipped += 1
            continue
        shutil.copy2(src, dst)
        copied += 1
    print(f"  drivelm: copied={copied}, skip-exist={skipped} → {DRIVELM_DST}")

# Per-camera mapping: short name → (JSON field name, raw-data tar prefix marker).
# JSON fields appear in the sample JSON files generated by the preprocessing step.
# Cameras not listed here are not currently supported.
NUPLAN_CAMERA_TO_FIELD = {
    "F0": "front_camera_paths",         # CAM_F0       (front)
    "L0": "front_left_camera_paths",    # CAM_L0       (45° front-canted left)
    "R0": "front_right_camera_paths",   # CAM_R0       (45° front-canted right)
    "L1": "left_camera_paths",          # CAM_L1       (90° pure side left)
    "R1": "right_camera_paths",         # CAM_R1       (90° pure side right)
    "B0": "back_camera_paths",          # CAM_B0       (back)
}
NUSC_CAMERA_TO_FIELD = {
    "front":       "front_camera_paths",        # samples/CAM_FRONT/
    "front_left":  "front_left_camera_paths",   # samples/CAM_FRONT_LEFT/
    "front_right": "front_right_camera_paths",  # samples/CAM_FRONT_RIGHT/
    "back":        "back_camera_paths",         # samples/CAM_BACK/
}
NUSC_CAMERA_TO_SAMPLE_PREFIX = {
    "front":       "samples/CAM_FRONT/",
    "front_left":  "samples/CAM_FRONT_LEFT/",
    "front_right": "samples/CAM_FRONT_RIGHT/",
    "back":        "samples/CAM_BACK/",
}

# Cameras / sensors we never want under any selection.
NUSC_BASE_SKIP_PREFIXES = (
    "sweeps/",
    "samples/LIDAR_TOP/",
    "samples/RADAR_FRONT/",
    "samples/RADAR_FRONT_LEFT/",
    "samples/RADAR_FRONT_RIGHT/",
    "samples/RADAR_BACK_LEFT/",
    "samples/RADAR_BACK_RIGHT/",
    "samples/CAM_BACK_LEFT/",
    "samples/CAM_BACK_RIGHT/",
)


def nusc_skip_prefixes(nuscenes_cameras):
    """Build the skip-prefix tuple given the keep-camera set.

    Any camera in NUSC_CAMERA_TO_SAMPLE_PREFIX that is NOT in nuscenes_cameras
    gets its samples/CAM_<X>/ path appended to the skip set.
    """
    kept = set(nuscenes_cameras)
    extras = tuple(
        prefix for cam, prefix in NUSC_CAMERA_TO_SAMPLE_PREFIX.items()
        if cam not in kept
    )
    return NUSC_BASE_SKIP_PREFIXES + extras


def used_fields(dataset, cameras=None, num_cameras=None):
    """JSON field names that hold the camera path arrays this workspace needs.

    Preferred call form: pass `cameras=` (list of short names) for explicit
    selection. Maps NUPLAN_CAMERA_TO_FIELD / NUSC_CAMERA_TO_FIELD.

    Backwards-compat: when `num_cameras` is set (3 or 4), expands to the
    legacy camera sets:
      nuplan   3 → [F0, L1, R1];   4 → [..., B0]
      nuscenes 3 → [front, FL, FR]; 4 → [..., back]
    """
    if cameras is None:
        if num_cameras is None:
            raise ValueError("used_fields() needs cameras= or num_cameras=")
        if dataset == "nuplan":
            cameras = ["F0", "L1", "R1"] + (["B0"] if num_cameras == 4 else [])
        elif dataset == "nuscenes":
            cameras = ["front", "front_left", "front_right"] + (["back"] if num_cameras == 4 else [])
        else:
            raise ValueError(f"Unknown dataset {dataset!r}")
        if num_cameras not in (3, 4):
            raise ValueError(f"num_cameras must be 3 or 4, got {num_cameras}")

    mapping = NUPLAN_CAMERA_TO_FIELD if dataset == "nuplan" else NUSC_CAMERA_TO_FIELD
    fields = []
    for cam in cameras:
        if cam not in mapping:
            raise ValueError(f"Unknown {dataset} camera {cam!r}; valid: {sorted(mapping)}")
        fields.append(mapping[cam])
    return tuple(fields)


# Module-level skip set used by the rest of the file. Recomputed in main() once
# the nuScenes camera list is known; default = legacy 3-camera training set.
NUSC_SKIP_PREFIXES = nusc_skip_prefixes(["front", "front_left", "front_right"])


def open_streaming_tar(tarball: Path):
    """Open a tarball for streaming reads (mode 'r|'). Returns (TarFile, decoder_proc).

    Decompression always runs in a subprocess (zstdcat / pigz / gzip) so that an
    8-way ThreadPool actually parallelizes — the alternative ('r|gz' built-in)
    holds the GIL across enough of the inflate loop to cap aggregate read at
    ~3× single-stream instead of the benchmark's 6-7×.
    """
    name = tarball.name
    if name.endswith(".tar.zst") or name.endswith(".tzst"):
        decompressor = ["zstdcat", str(tarball)]
    elif name.endswith(".tar.gz") or name.endswith(".tgz"):
        gz = "pigz" if shutil.which("pigz") else "gzip"
        decompressor = [gz, "-dc", str(tarball)]
    else:
        return tarfile.open(str(tarball), mode="r|"), None
    proc = subprocess.Popen(decompressor, stdout=subprocess.PIPE, bufsize=4 << 20)
    return tarfile.open(fileobj=proc.stdout, mode="r|"), proc


def stream_extract_filtered(tarball: Path, predicate, output_path_fn):
    """Stream tarball, extract members where predicate(name)==True to output_path_fn(name).
    Returns (written, skipped_already_exist, skipped_by_predicate)."""
    tar, proc = open_streaming_tar(tarball)
    written = 0
    skipped_exist = 0
    skipped_pred = 0
    try:
        for member in tar:
            if not member.isfile():
                continue
            if not predicate(member.name):
                skipped_pred += 1
                continue
            out = output_path_fn(member.name)
            if out is None:
                skipped_pred += 1
                continue
            if out.exists():
                skipped_exist += 1
                continue
            out.parent.mkdir(parents=True, exist_ok=True)
            f = tar.extractfile(member)
            if f is None:
                continue
            tmp = out.with_suffix(out.suffix + ".tmp")
            try:
                with open(tmp, "wb") as fout:
                    shutil.copyfileobj(f, fout, length=1 << 18)
                os.replace(tmp, out)
                written += 1
            finally:
                if tmp.exists():
                    tmp.unlink()
    finally:
        tar.close()
        if proc is not None:
            proc.wait()
    return written, skipped_exist, skipped_pred


def find_sample_tarball(scale: str, bucket: str, model: str) -> Path:
    scale_dir = BACKUP_SCALING_DIR / f"nuplan_nuscenes_train_mix_{scale}"
    patterns = {
        "nuplan_nocot":   "nuplan_action_only_samples_*.tar.zst",
        "nuplan_cot":     f"nuplan_nl_reasoning_samples_{model}_*.tar.zst",
        "nuscenes_nocot": "nuscenes_action_only_samples_*.tar.zst",
        "nuscenes_cot":   "nuscenes_nl_reasoning_samples_*.tar.zst",
    }
    pat = patterns[bucket]
    matches = list(scale_dir.glob(pat))
    if not matches:
        raise FileNotFoundError(f"No tarball matching {pat} in {scale_dir}")
    if len(matches) > 1:
        raise ValueError(f"Multiple matches for {pat}: {matches}")
    return matches[0]


def extract_sample_tarball(tarball: Path, target_subdir: Path, dataset_prefix: str) -> int:
    """Extract a sample-JSON tarball into target_subdir, stripping `<dataset_prefix>_`
    from the leading top-level directory name inside the archive."""
    strip = f"{dataset_prefix}_"
    n = 0
    tar, proc = open_streaming_tar(tarball)
    try:
        for member in tar:
            if not member.isfile():
                continue
            inner = member.name
            if inner.startswith(strip):
                inner = inner[len(strip):]
            out = target_subdir / inner
            out.parent.mkdir(parents=True, exist_ok=True)
            f = tar.extractfile(member)
            if f is None:
                continue
            with open(out, "wb") as fout:
                shutil.copyfileobj(f, fout, length=1 << 18)
            n += 1
    finally:
        tar.close()
        if proc is not None:
            proc.wait()
    return n


def collect_needed_raw_paths(workspace: Path, nuplan_cameras=None, nuscenes_cameras=None):
    """Walk the per-scale workspace JSONs, return:
      - nuplan_jpgs: set of absolute jpg paths under /data/nuPlan/sensor_blobs/trainval/
      - nuplan_pkls: set of absolute pkl paths under /data/nuPlan/navsim_logs/trainval/
      - nusc_jpgs:   set of absolute jpg paths under /data/nuScenes/samples/
    Each set is restricted to the requested camera list per dataset.

    JSON paths produced by the upstream pipeline use the legacy
    `/data/nuPlan/trainval_sensor_blobs/trainval/...` form; we translate them
    in-memory to the unified `/data/nuPlan/sensor_blobs/trainval/...` form so
    the in-memory set matches the destinations used by extract_raw_nuplan()
    below. Idempotent for JSONs that already use the new layout."""
    nuplan_jpgs = set()
    nuplan_scenes = set()
    nusc_jpgs = set()

    nuplan_fields = used_fields("nuplan", cameras=nuplan_cameras)
    nusc_fields = used_fields("nuscenes", cameras=nuscenes_cameras)

    for jpath in (workspace / "nuPlan").rglob("*.json"):
        with open(jpath) as f:
            d = json.load(f)
        for field in nuplan_fields:
            for p in d.get(field) or []:
                if not isinstance(p, str):
                    continue
                p_new = p.replace("/trainval_sensor_blobs/", "/sensor_blobs/")
                nuplan_jpgs.add(p_new)
                # /data/nuPlan/sensor_blobs/trainval/<scene>/CAM_*/<jpg>.jpg
                parts = p_new.split("/")
                try:
                    i = parts.index("sensor_blobs")
                    nuplan_scenes.add(parts[i + 2])  # skip "trainval/"
                except (ValueError, IndexError):
                    pass

    for jpath in (workspace / "nuScenes").rglob("*.json"):
        with open(jpath) as f:
            d = json.load(f)
        for field in nusc_fields:
            for p in d.get(field) or []:
                if not isinstance(p, str):
                    continue
                nusc_jpgs.add(p)

    nuplan_pkls = {
        str(NUPLAN_RAW / "navsim_logs" / "trainval" / f"{s}.pkl")
        for s in nuplan_scenes
    }
    return nuplan_jpgs, nuplan_pkls, nusc_jpgs, nuplan_scenes


def extract_raw_nuplan(jpgs: set, pkls: set, parallelism: int):
    # openscene tarballs are already nested by split internally:
    #   sensor: openscene-v1.1/sensor_blobs/trainval/<scene>/...
    #   meta:   openscene-v1.1/meta_datas/trainval/<log>.pkl
    # so stripping just the openscene prefix lands files in the unified
    # /data/nuPlan/{sensor_blobs,navsim_logs}/trainval/... layout.
    sensor_strip = "openscene-v1.1/sensor_blobs/"
    sensor_dest = NUPLAN_RAW / "sensor_blobs"
    meta_strip = "openscene-v1.1/meta_datas/"
    meta_dest = NUPLAN_RAW / "navsim_logs"

    def jpg_predicate(name):
        return name.startswith(sensor_strip) and name.endswith(".jpg")

    def jpg_output_fn(name):
        rel = name[len(sensor_strip):]
        full = sensor_dest / rel
        return full if str(full) in jpgs else None

    def pkl_predicate(name):
        return name.startswith(meta_strip) and name.endswith(".pkl")

    def pkl_output_fn(name):
        rel = name[len(meta_strip):]
        full = meta_dest / rel
        return full if str(full) in pkls else None

    missing_jpgs = sum(1 for p in jpgs if not Path(p).exists())
    missing_pkls = sum(1 for p in pkls if not Path(p).exists())
    print(f"  needed: {len(jpgs)} jpgs ({missing_jpgs} missing), "
          f"{len(pkls)} pkls ({missing_pkls} missing)")
    if missing_jpgs == 0 and missing_pkls == 0:
        print("  all needed nuplan raw files already on /data, skipping extraction.")
        return

    if missing_pkls > 0:
        meta_tar = BACKUP_RAW_NUPLAN / "openscene_metadata_trainval.tgz"
        print(f"  extracting nuplan metadata ({meta_tar.name}) ...")
        t0 = perf_counter()
        w, se, sp = stream_extract_filtered(meta_tar, pkl_predicate, pkl_output_fn)
        print(f"    wrote={w}, skip-exist={se}, skip-pred={sp}, "
              f"elapsed={perf_counter()-t0:.1f}s")

    if missing_jpgs > 0:
        # Sort by size desc so the biggest tarballs start first and overlap with
        # the long tail; otherwise the largest two finish strictly after the
        # smaller eight, adding ~5 min of single-stream tail latency.
        cams = sorted(
            BACKUP_RAW_NUPLAN.glob("openscene_sensor_trainval_camera_*.tgz"),
            key=lambda p: -p.stat().st_size,
        )
        print(f"  streaming {len(cams)} nuplan camera tarballs (parallel={parallelism}) ...")
        t0 = perf_counter()
        total = [0, 0, 0]
        with ThreadPoolExecutor(max_workers=parallelism) as pool:
            futs = {pool.submit(stream_extract_filtered, tb, jpg_predicate, jpg_output_fn): tb
                    for tb in cams}
            done = 0
            for fut in as_completed(futs):
                w, se, sp = fut.result()
                total[0] += w; total[1] += se; total[2] += sp
                done += 1
                if done % 20 == 0 or done == len(cams):
                    print(f"    progress: {done}/{len(cams)} tarballs, "
                          f"wrote={total[0]} skip-exist={total[1]}, "
                          f"elapsed={perf_counter()-t0:.1f}s")
        print(f"    final: wrote={total[0]}, skip-exist={total[1]}, skip-pred={total[2]}, "
              f"elapsed={perf_counter()-t0:.1f}s")


def extract_raw_nuscenes(jpgs: set, parallelism: int):
    def jpg_predicate(name):
        if any(name.startswith(p) for p in NUSC_SKIP_PREFIXES):
            return False
        return name.startswith("samples/") and name.endswith(".jpg")

    def jpg_output_fn(name):
        full = NUSC_RAW / name
        return full if str(full) in jpgs else None

    def meta_predicate(name):
        if any(name.startswith(p) for p in NUSC_SKIP_PREFIXES):
            return False
        return True

    def meta_output_fn(name):
        return NUSC_RAW / name

    # Always stream meta tarball — it's small and idempotent.
    meta_tar = BACKUP_RAW_NUSC / "v1.0-trainval_meta.tgz"
    print(f"  extracting {meta_tar.name} ...")
    t0 = perf_counter()
    w, se, sp = stream_extract_filtered(meta_tar, meta_predicate, meta_output_fn)
    print(f"    wrote={w}, skip-exist={se}, skip-pred={sp}, "
          f"elapsed={perf_counter()-t0:.1f}s")

    missing = sum(1 for p in jpgs if not Path(p).exists())
    print(f"  needed: {len(jpgs)} jpgs ({missing} missing)")
    if missing == 0:
        print("  all needed nuscenes jpgs already on /data, skipping blob extraction.")
        return

    # Largest first — trainval10 (39G) and trainval09 (32G) dominate tail latency.
    blobs = sorted(
        BACKUP_RAW_NUSC.glob("v1.0-trainval[0-9]*_blobs.tgz"),
        key=lambda p: -p.stat().st_size,
    )
    print(f"  streaming {len(blobs)} nuscenes trainval blobs (parallel={parallelism}) ...")
    t0 = perf_counter()
    total = [0, 0, 0]
    with ThreadPoolExecutor(max_workers=parallelism) as pool:
        futs = {pool.submit(stream_extract_filtered, tb, jpg_predicate, jpg_output_fn): tb
                for tb in blobs}
        done = 0
        for fut in as_completed(futs):
            w, se, sp = fut.result()
            total[0] += w; total[1] += se; total[2] += sp
            done += 1
            print(f"    progress: {done}/{len(blobs)} blobs, wrote={total[0]} "
                  f"skip-exist={total[1]}, elapsed={perf_counter()-t0:.1f}s")
    print(f"    final: wrote={total[0]}, skip-exist={total[1]}, skip-pred={total[2]}, "
          f"elapsed={perf_counter()-t0:.1f}s")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--scale", required=True, choices=SCALES)
    p.add_argument("--model", required=True,
                   help="CoT model substring matched against the nuplan_cot tarball name "
                        "(e.g. Qwen2.4_VL_72B_Instruct_AWQ).")
    p.add_argument("--parallelism", type=int, default=8,
                   help="Number of tarballs streamed concurrently (per benchmark, 8 is optimal).")
    p.add_argument("--force", action="store_true",
                   help="rm -rf the per-scale workspace before starting.")
    p.add_argument("--skip-raw", action="store_true",
                   help="Skip raw-data extraction (only build the per-scale JSON workspace).")
    p.add_argument("--num-cameras", type=int, choices=(3, 4), default=None,
                   help="Backwards-compat alias. 3 = legacy SFT/RL training set "
                        "(nuPlan F0+L1+R1, nuScenes front+front_left+front_right). "
                        "4 = adds back. Mutually exclusive with --nuplan-cameras / "
                        "--nuscenes-cameras. Use those instead for finer control.")
    p.add_argument("--nuplan-cameras", type=str, default=None,
                   help="Comma-separated nuPlan cameras to hydrate. Valid: "
                        f"{','.join(NUPLAN_CAMERA_TO_FIELD.keys())}. Example: "
                        "'F0,L1,R1,B0' for 4-view 90° teacher. Defaults to "
                        "the --num-cameras-derived set when omitted.")
    p.add_argument("--nuscenes-cameras", type=str, default=None,
                   help="Comma-separated nuScenes cameras to hydrate. Valid: "
                        f"{','.join(NUSC_CAMERA_TO_FIELD.keys())}. Example: "
                        "'front,front_left,front_right,back' for 4-view teacher.")
    p.add_argument("--datasets", choices=DATASETS, default="both",
                   help="Which dataset(s) to hydrate. 'nuplan' or 'nuscenes' "
                        "loads only that side; 'both' (default) loads the full "
                        "mix. nuScenes also pulls /backup/drivelm/ → /data/drivelm/.")
    args = p.parse_args()

    want_nuplan = args.datasets in ("nuplan", "both")
    want_nusc   = args.datasets in ("nuscenes", "both")

    # Resolve camera selection: explicit lists override --num-cameras.
    def _parse_list(spec, valid, label):
        items = [s.strip() for s in spec.split(",") if s.strip()]
        bad = [s for s in items if s not in valid]
        if bad:
            p.error(f"Unknown {label} camera(s): {bad}; valid: {sorted(valid)}")
        return items

    if args.nuplan_cameras is not None or args.nuscenes_cameras is not None:
        if args.num_cameras is not None:
            p.error("--num-cameras is mutually exclusive with --nuplan-cameras / --nuscenes-cameras")
        nuplan_cameras = _parse_list(
            args.nuplan_cameras or "F0,L1,R1", NUPLAN_CAMERA_TO_FIELD, "nuplan"
        )
        nuscenes_cameras = _parse_list(
            args.nuscenes_cameras or "front,front_left,front_right", NUSC_CAMERA_TO_FIELD, "nuscenes"
        )
    else:
        # Legacy --num-cameras (or omitted → defaults to 3)
        legacy_n = args.num_cameras if args.num_cameras is not None else 3
        if legacy_n == 3:
            nuplan_cameras = ["F0", "L1", "R1"]
            nuscenes_cameras = ["front", "front_left", "front_right"]
        else:  # 4
            nuplan_cameras = ["F0", "L1", "R1", "B0"]
            nuscenes_cameras = ["front", "front_left", "front_right", "back"]

    print(f"  nuplan cameras:   {nuplan_cameras}")
    print(f"  nuscenes cameras: {nuscenes_cameras}")

    # Rebind module-level skip set so extract_raw_nuscenes() sees the right
    # filter even though it doesn't take a parameter.
    global NUSC_SKIP_PREFIXES
    NUSC_SKIP_PREFIXES = nusc_skip_prefixes(nuscenes_cameras)

    workspace = DATA_ROOT / f"nuplan_nuscenes_train_mix_{args.scale}"
    print(f"workspace: {workspace}  (datasets={args.datasets})")
    if args.force and workspace.exists():
        print(f"--force: removing {workspace}")
        shutil.rmtree(workspace)
    workspace.mkdir(parents=True, exist_ok=True)
    if want_nuplan:
        (workspace / "nuPlan").mkdir(exist_ok=True)
    if want_nusc:
        (workspace / "nuScenes").mkdir(exist_ok=True)

    # Phase 1
    print(f"\n=== Phase 1: sample-JSON tarballs → {workspace} ===")
    t1 = perf_counter()
    all_specs = [
        ("nuplan_nocot",   "nuplan",   workspace / "nuPlan"),
        ("nuplan_cot",     "nuplan",   workspace / "nuPlan"),
        ("nuscenes_nocot", "nuscenes", workspace / "nuScenes"),
        ("nuscenes_cot",   "nuscenes", workspace / "nuScenes"),
    ]
    bucket_specs = [s for s in all_specs
                    if (s[1] == "nuplan" and want_nuplan)
                    or (s[1] == "nuscenes" and want_nusc)]
    with ThreadPoolExecutor(max_workers=max(1, len(bucket_specs))) as pool:
        futs = {}
        for bucket, ds, tgt in bucket_specs:
            tb = find_sample_tarball(args.scale, bucket, args.model)
            futs[pool.submit(extract_sample_tarball, tb, tgt, ds)] = (bucket, tb)
        for fut in as_completed(futs):
            bucket, tb = futs[fut]
            n = fut.result()
            print(f"  [{bucket:>14s}] {tb.name}: extracted {n} files")

    splits_src = (BACKUP_SCALING_DIR / f"nuplan_nuscenes_train_mix_{args.scale}"
                  / f"scaling_{args.scale}_token_list.json")
    shutil.copy2(splits_src, workspace / splits_src.name)
    print(f"  copied {splits_src.name}")
    print(f"  Phase 1 elapsed: {perf_counter()-t1:.1f}s")

    # drivelm travels with nuScenes (JSON-only artifact; sync even under --skip-raw)
    if want_nusc:
        print(f"\n=== drivelm sync: {BACKUP_DRIVELM} → {DRIVELM_DST} ===")
        sync_drivelm()

    if args.skip_raw:
        print("\n--skip-raw set; done.")
        return 0

    # Phase 2
    print(f"\n=== Phase 2: compute needed raw paths (nuplan={nuplan_cameras}, nuscenes={nuscenes_cameras}) ===")
    t2 = perf_counter()
    nuplan_jpgs, nuplan_pkls, nusc_jpgs, nuplan_scenes = collect_needed_raw_paths(
        workspace,
        nuplan_cameras=nuplan_cameras,
        nuscenes_cameras=nuscenes_cameras,
    )
    print(f"  nuplan: {len(nuplan_jpgs)} jpgs, {len(nuplan_scenes)} scenes ({len(nuplan_pkls)} pkls)")
    print(f"  nuscenes: {len(nusc_jpgs)} jpgs")
    print(f"  Phase 2 elapsed: {perf_counter()-t2:.1f}s")

    # Phase 3
    if want_nuplan:
        print(f"\n=== Phase 3: raw nuPlan → /data/nuPlan/ ===")
        t3 = perf_counter()
        extract_raw_nuplan(nuplan_jpgs, nuplan_pkls, args.parallelism)
        print(f"  Phase 3 elapsed: {perf_counter()-t3:.1f}s")

    # Phase 4
    if want_nusc:
        print(f"\n=== Phase 4: raw nuScenes → /data/nuScenes/ ===")
        t4 = perf_counter()
        extract_raw_nuscenes(nusc_jpgs, args.parallelism)
        print(f"  Phase 4 elapsed: {perf_counter()-t4:.1f}s")

    # Verify
    print(f"\n=== Verification ===")
    miss_np = sum(1 for p in nuplan_jpgs if not Path(p).exists()) if want_nuplan else 0
    miss_pk = sum(1 for p in nuplan_pkls if not Path(p).exists()) if want_nuplan else 0
    miss_ns = sum(1 for p in nusc_jpgs   if not Path(p).exists()) if want_nusc   else 0
    print(f"  missing: nuplan jpgs={miss_np}, nuplan pkls={miss_pk}, nuscenes jpgs={miss_ns}")
    if miss_np or miss_pk or miss_ns:
        print("  WARNING: some needed files are missing")
        return 1
    print("  all needed files present.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
